"""initial MVP schema

Revision ID: 0001
Revises:
Create Date: 2026-07-20 21:11:02.633831
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysts",
        sa.Column("analyst_id", sa.String(length=16), nullable=False),
        sa.Column("canonical_name", sa.String(length=200), nullable=False),
        sa.Column("normalized_name", sa.String(length=200), nullable=False),
        sa.Column("aliases", sa.JSON(), nullable=False),
        sa.Column("affiliation", sa.String(length=200), nullable=True),
        sa.Column("specialties", sa.JSON(), nullable=False),
        sa.Column("official_youtube", sa.Text(), nullable=True),
        sa.Column("official_blog", sa.Text(), nullable=True),
        sa.Column("official_x", sa.Text(), nullable=True),
        sa.Column("profile_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("analyst_id"),
        sa.UniqueConstraint("normalized_name"),
    )
    op.create_table(
        "id_sequences",
        sa.Column("sequence_key", sa.String(length=32), nullable=False),
        sa.Column("current_value", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("sequence_key"),
    )
    op.create_table(
        "market_series",
        sa.Column("market_series_id", sa.String(length=20), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("symbol", sa.String(length=100), nullable=False),
        sa.Column("currency", sa.String(length=20), nullable=False),
        sa.Column("adjustment_type", sa.String(length=60), nullable=False),
        sa.Column("frequency", sa.String(length=20), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_cache_path", sa.Text(), nullable=False),
        sa.Column("data_hash", sa.String(length=64), nullable=False),
        sa.Column("quality_status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("market_series_id"),
    )
    with op.batch_alter_table("market_series", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_market_series_data_hash"), ["data_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_market_series_provider"), ["provider"], unique=False)
        batch_op.create_index(batch_op.f("ix_market_series_symbol"), ["symbol"], unique=False)

    op.create_table(
        "targets",
        sa.Column("target_id", sa.String(length=20), nullable=False),
        sa.Column("raw_label", sa.Text(), nullable=False),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("target_type", sa.String(length=40), nullable=False),
        sa.Column("ticker", sa.String(length=100), nullable=False),
        sa.Column("security_code", sa.String(length=100), nullable=True),
        sa.Column("exchange", sa.String(length=100), nullable=True),
        sa.Column("currency", sa.String(length=20), nullable=False),
        sa.Column("aliases", sa.JSON(), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("target_id"),
        sa.UniqueConstraint("canonical_name", "ticker", "currency", name="uq_target_identity"),
    )
    with op.batch_alter_table("targets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_targets_target_type"), ["target_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_targets_ticker"), ["ticker"], unique=False)

    op.create_table(
        "forecast_groups",
        sa.Column("forecast_group_id", sa.String(length=20), nullable=False),
        sa.Column("analyst_id", sa.String(length=16), nullable=False),
        sa.Column("central_thesis", sa.Text(), nullable=False),
        sa.Column("first_issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("latest_issued_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("current_stance", sa.String(length=20), nullable=True),
        sa.Column("reaffirmation_count", sa.Integer(), nullable=False),
        sa.Column("revision_count", sa.Integer(), nullable=False),
        sa.Column("withdrawal_status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analyst_id"],
            ["analysts.analyst_id"],
        ),
        sa.PrimaryKeyConstraint("forecast_group_id"),
    )
    with op.batch_alter_table("forecast_groups", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_forecast_groups_analyst_id"), ["analyst_id"], unique=False
        )

    op.create_table(
        "runs",
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("analyst_id", sa.String(length=16), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("evaluation_as_of", sa.Date(), nullable=False),
        sa.Column("selected_media", sa.JSON(), nullable=False),
        sa.Column("focus_targets", sa.JSON(), nullable=False),
        sa.Column("ai_environment", sa.JSON(), nullable=False),
        sa.Column("model_configuration", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("run_path", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analyst_id"],
            ["analysts.analyst_id"],
        ),
        sa.PrimaryKeyConstraint("run_id"),
        sa.UniqueConstraint("run_path"),
    )
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_runs_analyst_id"), ["analyst_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_runs_status"), ["status"], unique=False)

    op.create_table(
        "sources",
        sa.Column("source_id", sa.String(length=20), nullable=False),
        sa.Column("analyst_id", sa.String(length=16), nullable=False),
        sa.Column("medium", sa.String(length=20), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("external_source_id", sa.String(length=300), nullable=True),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("publisher_or_channel", sa.String(length=300), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evidence_level", sa.String(length=8), nullable=True),
        sa.Column("raw_file_path", sa.Text(), nullable=False),
        sa.Column("raw_hash", sa.String(length=64), nullable=False),
        sa.Column("acquisition_status", sa.String(length=40), nullable=False),
        sa.Column("source_relation", sa.String(length=40), nullable=False),
        sa.Column("original_source_id", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analyst_id"],
            ["analysts.analyst_id"],
        ),
        sa.ForeignKeyConstraint(
            ["original_source_id"],
            ["sources.source_id"],
        ),
        sa.PrimaryKeyConstraint("source_id"),
    )
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sources_analyst_id"), ["analyst_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_sources_medium"), ["medium"], unique=False)
        batch_op.create_index(batch_op.f("ix_sources_raw_hash"), ["raw_hash"], unique=True)

    op.create_table(
        "target_mappings",
        sa.Column("target_mapping_id", sa.String(length=20), nullable=False),
        sa.Column("target_id", sa.String(length=20), nullable=False),
        sa.Column("mapping_method", sa.String(length=40), nullable=False),
        sa.Column("evaluation_instruments", sa.JSON(), nullable=False),
        sa.Column("weights", sa.JSON(), nullable=True),
        sa.Column("benchmark", sa.String(length=100), nullable=True),
        sa.Column("knowledge_cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_evidence", sa.Text(), nullable=False),
        sa.Column("proposal_model", sa.String(length=200), nullable=True),
        sa.Column("review_result", sa.Text(), nullable=True),
        sa.Column("adjudication_result", sa.Text(), nullable=True),
        sa.Column("mapping_status", sa.String(length=40), nullable=False),
        sa.Column("mapping_hash", sa.String(length=64), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["targets.target_id"],
        ),
        sa.PrimaryKeyConstraint("target_mapping_id"),
    )
    with op.batch_alter_table("target_mappings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_target_mappings_mapping_hash"), ["mapping_hash"], unique=True
        )
        batch_op.create_index(
            batch_op.f("ix_target_mappings_mapping_status"), ["mapping_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_target_mappings_target_id"), ["target_id"], unique=False
        )

    op.create_table(
        "ai_imports",
        sa.Column("ai_import_id", sa.String(length=20), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.String(length=20), nullable=False),
        sa.Column("output_hash", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=20), nullable=False),
        sa.Column("classified_file_path", sa.Text(), nullable=False),
        sa.Column("classification", sa.String(length=30), nullable=False),
        sa.Column("validation_status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
        ),
        sa.PrimaryKeyConstraint("ai_import_id"),
    )
    with op.batch_alter_table("ai_imports", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_ai_imports_output_hash"), ["output_hash"], unique=True)
        batch_op.create_index(batch_op.f("ix_ai_imports_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ai_imports_source_id"), ["source_id"], unique=False)

    op.create_table(
        "run_sources",
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.String(length=20), nullable=False),
        sa.Column("observed_url", sa.Text(), nullable=True),
        sa.Column("observed_medium", sa.String(length=20), nullable=False),
        sa.Column("observed_published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("linked_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
        ),
        sa.PrimaryKeyConstraint("run_id", "source_id"),
    )
    op.create_table(
        "forecast_issuances",
        sa.Column("forecast_issuance_id", sa.String(length=20), nullable=False),
        sa.Column("analyst_id", sa.String(length=16), nullable=False),
        sa.Column("forecast_group_id", sa.String(length=20), nullable=False),
        sa.Column("ai_import_id", sa.String(length=20), nullable=False),
        sa.Column("source_id", sa.String(length=20), nullable=False),
        sa.Column("local_ref", sa.String(length=100), nullable=False),
        sa.Column("made_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("publicly_available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("forecast_type", sa.String(length=40), nullable=False),
        sa.Column("commitment_strength", sa.String(length=40), nullable=False),
        sa.Column("evidence_level", sa.String(length=8), nullable=False),
        sa.Column("extraction_confidence", sa.Float(), nullable=False),
        sa.Column("human_readable_summary", sa.Text(), nullable=False),
        sa.Column("relation_to_previous", sa.String(length=40), nullable=False),
        sa.Column("current_status", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ai_import_id"],
            ["ai_imports.ai_import_id"],
        ),
        sa.ForeignKeyConstraint(
            ["analyst_id"],
            ["analysts.analyst_id"],
        ),
        sa.ForeignKeyConstraint(
            ["forecast_group_id"],
            ["forecast_groups.forecast_group_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
        ),
        sa.PrimaryKeyConstraint("forecast_issuance_id"),
        sa.UniqueConstraint("ai_import_id", "local_ref", name="uq_issuance_import_ref"),
    )
    with op.batch_alter_table("forecast_issuances", schema=None) as batch_op:
        batch_op.create_index(
            "ix_forecast_issuance_analyst_status", ["analyst_id", "current_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_forecast_issuances_analyst_id"), ["analyst_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_forecast_issuances_current_status"), ["current_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_forecast_issuances_forecast_group_id"),
            ["forecast_group_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_forecast_issuances_source_id"), ["source_id"], unique=False
        )

    op.create_table(
        "prompt_executions",
        sa.Column("prompt_execution_id", sa.String(length=20), nullable=False),
        sa.Column("ai_import_id", sa.String(length=20), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("prompt_id", sa.String(length=20), nullable=False),
        sa.Column("prompt_version", sa.String(length=20), nullable=False),
        sa.Column("environment", sa.String(length=20), nullable=False),
        sa.Column("model", sa.String(length=200), nullable=False),
        sa.Column("input_files", sa.JSON(), nullable=False),
        sa.Column("output_file", sa.Text(), nullable=False),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("validation_status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ai_import_id"],
            ["ai_imports.ai_import_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.run_id"],
        ),
        sa.PrimaryKeyConstraint("prompt_execution_id"),
        sa.UniqueConstraint("ai_import_id"),
    )
    with op.batch_alter_table("prompt_executions", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_prompt_executions_run_id"), ["run_id"], unique=False)

    op.create_table(
        "forecast_components",
        sa.Column("forecast_component_id", sa.String(length=20), nullable=False),
        sa.Column("forecast_issuance_id", sa.String(length=20), nullable=False),
        sa.Column("parent_component_id", sa.String(length=20), nullable=True),
        sa.Column("local_ref", sa.String(length=100), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("prediction_form", sa.String(length=40), nullable=False),
        sa.Column("direction", sa.String(length=20), nullable=False),
        sa.Column("time_expression_raw", sa.Text(), nullable=True),
        sa.Column("time_source", sa.String(length=30), nullable=False),
        sa.Column("normalized_start", sa.Date(), nullable=True),
        sa.Column("normalized_end", sa.Date(), nullable=True),
        sa.Column("time_precision", sa.String(length=30), nullable=True),
        sa.Column("magnitude_value", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("magnitude_unit", sa.String(length=40), nullable=True),
        sa.Column("magnitude_operator", sa.String(length=40), nullable=True),
        sa.Column("scenario_probability", sa.Float(), nullable=True),
        sa.Column("target_id", sa.String(length=20), nullable=False),
        sa.Column("target_mapping_id", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["forecast_issuance_id"],
            ["forecast_issuances.forecast_issuance_id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_component_id"],
            ["forecast_components.forecast_component_id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["targets.target_id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_mapping_id"],
            ["target_mappings.target_mapping_id"],
        ),
        sa.PrimaryKeyConstraint("forecast_component_id"),
        sa.UniqueConstraint("forecast_issuance_id", "local_ref", name="uq_component_ref"),
    )
    with op.batch_alter_table("forecast_components", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_forecast_components_forecast_issuance_id"),
            ["forecast_issuance_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_forecast_components_target_id"), ["target_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_forecast_components_target_mapping_id"),
            ["target_mapping_id"],
            unique=False,
        )

    op.create_table(
        "forecast_evidence",
        sa.Column("forecast_evidence_id", sa.String(length=20), nullable=False),
        sa.Column("forecast_issuance_id", sa.String(length=20), nullable=False),
        sa.Column("source_id", sa.String(length=20), nullable=False),
        sa.Column("quote", sa.Text(), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=False),
        sa.Column("end_offset", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=40), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["forecast_issuance_id"],
            ["forecast_issuances.forecast_issuance_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
        ),
        sa.PrimaryKeyConstraint("forecast_evidence_id"),
    )
    with op.batch_alter_table("forecast_evidence", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_forecast_evidence_forecast_issuance_id"),
            ["forecast_issuance_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_forecast_evidence_source_id"), ["source_id"], unique=False
        )

    op.create_table(
        "evaluations",
        sa.Column("evaluation_id", sa.String(length=20), nullable=False),
        sa.Column("forecast_component_id", sa.String(length=20), nullable=False),
        sa.Column("target_mapping_id", sa.String(length=20), nullable=False),
        sa.Column("market_series_id", sa.String(length=20), nullable=True),
        sa.Column("evaluation_method_version", sa.String(length=20), nullable=False),
        sa.Column("evaluation_as_of", sa.Date(), nullable=False),
        sa.Column("start_price", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("end_price", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("current_price", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("period_high", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("period_low", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("actual_return", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("total_return", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("base_currency_return", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("benchmark_return", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("excess_return", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("direction_result", sa.String(length=20), nullable=True),
        sa.Column("timing_result", sa.String(length=40), nullable=True),
        sa.Column("magnitude_result", sa.String(length=40), nullable=True),
        sa.Column("early_realization_result", sa.String(length=40), nullable=True),
        sa.Column("evaluation_status", sa.String(length=40), nullable=False),
        sa.Column("unevaluable_reason", sa.Text(), nullable=True),
        sa.Column("max_favorable_excursion", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("max_adverse_excursion", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["forecast_component_id"],
            ["forecast_components.forecast_component_id"],
        ),
        sa.ForeignKeyConstraint(
            ["market_series_id"],
            ["market_series.market_series_id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_mapping_id"],
            ["target_mappings.target_mapping_id"],
        ),
        sa.PrimaryKeyConstraint("evaluation_id"),
        sa.UniqueConstraint(
            "forecast_component_id",
            "target_mapping_id",
            "evaluation_method_version",
            "evaluation_as_of",
            name="uq_evaluation_identity",
        ),
    )
    with op.batch_alter_table("evaluations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_evaluations_evaluation_as_of"), ["evaluation_as_of"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_evaluations_evaluation_status"), ["evaluation_status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_evaluations_forecast_component_id"),
            ["forecast_component_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_evaluations_target_mapping_id"), ["target_mapping_id"], unique=False
        )

    op.create_table(
        "evaluation_snapshots",
        sa.Column("evaluation_snapshot_id", sa.String(length=20), nullable=False),
        sa.Column("evaluation_id", sa.String(length=20), nullable=False),
        sa.Column("snapshot_at", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("interim_return", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("max_favorable_excursion", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("max_adverse_excursion", sa.Numeric(precision=24, scale=10), nullable=True),
        sa.Column("first_realization_at", sa.Date(), nullable=True),
        sa.Column("days_early_or_late", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.evaluation_id"],
        ),
        sa.PrimaryKeyConstraint("evaluation_snapshot_id"),
        sa.UniqueConstraint("evaluation_id", "snapshot_at", name="uq_evaluation_snapshot"),
    )
    with op.batch_alter_table("evaluation_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_evaluation_snapshots_evaluation_id"), ["evaluation_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("evaluation_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evaluation_snapshots_evaluation_id"))

    op.drop_table("evaluation_snapshots")
    with op.batch_alter_table("evaluations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_evaluations_target_mapping_id"))
        batch_op.drop_index(batch_op.f("ix_evaluations_forecast_component_id"))
        batch_op.drop_index(batch_op.f("ix_evaluations_evaluation_status"))
        batch_op.drop_index(batch_op.f("ix_evaluations_evaluation_as_of"))

    op.drop_table("evaluations")
    with op.batch_alter_table("forecast_evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_forecast_evidence_source_id"))
        batch_op.drop_index(batch_op.f("ix_forecast_evidence_forecast_issuance_id"))

    op.drop_table("forecast_evidence")
    with op.batch_alter_table("forecast_components", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_forecast_components_target_mapping_id"))
        batch_op.drop_index(batch_op.f("ix_forecast_components_target_id"))
        batch_op.drop_index(batch_op.f("ix_forecast_components_forecast_issuance_id"))

    op.drop_table("forecast_components")
    with op.batch_alter_table("prompt_executions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_prompt_executions_run_id"))

    op.drop_table("prompt_executions")
    with op.batch_alter_table("forecast_issuances", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_forecast_issuances_source_id"))
        batch_op.drop_index(batch_op.f("ix_forecast_issuances_forecast_group_id"))
        batch_op.drop_index(batch_op.f("ix_forecast_issuances_current_status"))
        batch_op.drop_index(batch_op.f("ix_forecast_issuances_analyst_id"))
        batch_op.drop_index("ix_forecast_issuance_analyst_status")

    op.drop_table("forecast_issuances")
    op.drop_table("run_sources")
    with op.batch_alter_table("ai_imports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_imports_source_id"))
        batch_op.drop_index(batch_op.f("ix_ai_imports_run_id"))
        batch_op.drop_index(batch_op.f("ix_ai_imports_output_hash"))

    op.drop_table("ai_imports")
    with op.batch_alter_table("target_mappings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_target_mappings_target_id"))
        batch_op.drop_index(batch_op.f("ix_target_mappings_mapping_status"))
        batch_op.drop_index(batch_op.f("ix_target_mappings_mapping_hash"))

    op.drop_table("target_mappings")
    with op.batch_alter_table("sources", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sources_raw_hash"))
        batch_op.drop_index(batch_op.f("ix_sources_medium"))
        batch_op.drop_index(batch_op.f("ix_sources_analyst_id"))

    op.drop_table("sources")
    with op.batch_alter_table("runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_runs_status"))
        batch_op.drop_index(batch_op.f("ix_runs_analyst_id"))

    op.drop_table("runs")
    with op.batch_alter_table("forecast_groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_forecast_groups_analyst_id"))

    op.drop_table("forecast_groups")
    with op.batch_alter_table("targets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_targets_ticker"))
        batch_op.drop_index(batch_op.f("ix_targets_target_type"))

    op.drop_table("targets")
    with op.batch_alter_table("market_series", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_market_series_symbol"))
        batch_op.drop_index(batch_op.f("ix_market_series_provider"))
        batch_op.drop_index(batch_op.f("ix_market_series_data_hash"))

    op.drop_table("market_series")
    op.drop_table("id_sequences")
    op.drop_table("analysts")
    # ### end Alembic commands ###
