"""separate AI pipeline artifacts

Revision ID: 0002
Revises: 0001
Create Date: 2026-07-20 23:01:37.971184
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0002"
down_revision: str | Sequence[str] | None = "0001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_artifacts",
        sa.Column("ai_artifact_id", sa.String(length=20), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.String(length=20), nullable=True),
        sa.Column("prompt_execution_id", sa.String(length=20), nullable=False),
        sa.Column("prompt_id", sa.String(length=20), nullable=False),
        sa.Column("schema_version", sa.String(length=20), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("output_hash", sa.String(length=64), nullable=False),
        sa.Column("classified_file_path", sa.Text(), nullable=False),
        sa.Column("classification", sa.String(length=30), nullable=False),
        sa.Column("resolution_status", sa.String(length=40), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("importance", sa.String(length=20), nullable=False),
        sa.Column("high_importance_reason", sa.Text(), nullable=True),
        sa.Column("knowledge_cutoff", sa.DateTime(timezone=True), nullable=True),
        sa.Column("supersedes_artifact_id", sa.String(length=20), nullable=True),
        sa.Column("resolved_by_artifact_id", sa.String(length=20), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["prompt_execution_id"],
            ["prompt_executions.prompt_execution_id"],
        ),
        sa.ForeignKeyConstraint(
            ["resolved_by_artifact_id"],
            ["ai_artifacts.ai_artifact_id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.run_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_artifact_id"],
            ["ai_artifacts.ai_artifact_id"],
        ),
        sa.PrimaryKeyConstraint("ai_artifact_id"),
        sa.UniqueConstraint("prompt_execution_id"),
    )
    with op.batch_alter_table("ai_artifacts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ai_artifacts_classification"), ["classification"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ai_artifacts_output_hash"), ["output_hash"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_ai_artifacts_prompt_id"), ["prompt_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_ai_artifacts_resolution_status"), ["resolution_status"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_ai_artifacts_run_id"), ["run_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_ai_artifacts_source_id"), ["source_id"], unique=False)

    op.create_table(
        "segments",
        sa.Column("segment_id", sa.String(length=20), nullable=False),
        sa.Column("ai_artifact_id", sa.String(length=20), nullable=False),
        sa.Column("source_id", sa.String(length=20), nullable=False),
        sa.Column("local_ref", sa.String(length=100), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("raw_start_offset", sa.Integer(), nullable=False),
        sa.Column("raw_end_offset", sa.Integer(), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("normalized_text", sa.Text(), nullable=False),
        sa.Column("speaker_status", sa.String(length=30), nullable=False),
        sa.Column("speaker_candidate", sa.String(length=200), nullable=True),
        sa.Column("speaker_confidence", sa.Float(), nullable=False),
        sa.Column("attribution_basis", sa.Text(), nullable=False),
        sa.Column("review_status", sa.String(length=30), nullable=False),
        sa.Column("importance", sa.String(length=20), nullable=False),
        sa.Column("high_importance_reason", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ai_artifact_id"],
            ["ai_artifacts.ai_artifact_id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.source_id"],
        ),
        sa.PrimaryKeyConstraint("segment_id"),
        sa.UniqueConstraint("ai_artifact_id", "local_ref", name="uq_segment_artifact_ref"),
    )
    with op.batch_alter_table("segments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_segments_ai_artifact_id"), ["ai_artifact_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_segments_source_id"), ["source_id"], unique=False)

    op.create_table(
        "target_resolution_adjudications",
        sa.Column("target_resolution_adjudication_id", sa.String(length=20), nullable=False),
        sa.Column("adjudication_artifact_id", sa.String(length=20), nullable=False),
        sa.Column("proposal_artifact_id", sa.String(length=20), nullable=False),
        sa.Column("review_artifact_id", sa.String(length=20), nullable=False),
        sa.Column("forecast_component_id", sa.String(length=20), nullable=False),
        sa.Column("final_status", sa.String(length=30), nullable=False),
        sa.Column("selected_candidate_ref", sa.String(length=100), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["adjudication_artifact_id"],
            ["ai_artifacts.ai_artifact_id"],
        ),
        sa.ForeignKeyConstraint(
            ["forecast_component_id"],
            ["forecast_components.forecast_component_id"],
        ),
        sa.ForeignKeyConstraint(
            ["proposal_artifact_id"],
            ["ai_artifacts.ai_artifact_id"],
        ),
        sa.ForeignKeyConstraint(
            ["review_artifact_id"],
            ["ai_artifacts.ai_artifact_id"],
        ),
        sa.PrimaryKeyConstraint("target_resolution_adjudication_id"),
    )
    with op.batch_alter_table("target_resolution_adjudications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_target_resolution_adjudications_adjudication_artifact_id"),
            ["adjudication_artifact_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_target_resolution_adjudications_forecast_component_id"),
            ["forecast_component_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_target_resolution_adjudications_proposal_artifact_id"),
            ["proposal_artifact_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_target_resolution_adjudications_review_artifact_id"),
            ["review_artifact_id"],
            unique=False,
        )

    op.create_table(
        "target_resolution_candidates",
        sa.Column("target_resolution_candidate_id", sa.String(length=20), nullable=False),
        sa.Column("proposal_artifact_id", sa.String(length=20), nullable=False),
        sa.Column("forecast_component_id", sa.String(length=20), nullable=False),
        sa.Column("candidate_ref", sa.String(length=100), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("canonical_name", sa.Text(), nullable=False),
        sa.Column("target_type", sa.String(length=40), nullable=False),
        sa.Column("mapping_method", sa.String(length=40), nullable=False),
        sa.Column("instruments", sa.JSON(), nullable=False),
        sa.Column("existed_at", sa.Date(), nullable=False),
        sa.Column("knowledge_cutoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_evidence", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("candidate_status", sa.String(length=30), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["forecast_component_id"],
            ["forecast_components.forecast_component_id"],
        ),
        sa.ForeignKeyConstraint(
            ["proposal_artifact_id"],
            ["ai_artifacts.ai_artifact_id"],
        ),
        sa.PrimaryKeyConstraint("target_resolution_candidate_id"),
        sa.UniqueConstraint(
            "proposal_artifact_id", "candidate_ref", name="uq_target_candidate_artifact_ref"
        ),
    )
    with op.batch_alter_table("target_resolution_candidates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_target_resolution_candidates_forecast_component_id"),
            ["forecast_component_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_target_resolution_candidates_proposal_artifact_id"),
            ["proposal_artifact_id"],
            unique=False,
        )

    op.create_table(
        "target_resolution_reviews",
        sa.Column("target_resolution_review_id", sa.String(length=20), nullable=False),
        sa.Column("review_artifact_id", sa.String(length=20), nullable=False),
        sa.Column("proposal_artifact_id", sa.String(length=20), nullable=False),
        sa.Column("forecast_component_id", sa.String(length=20), nullable=False),
        sa.Column("candidate_ref", sa.String(length=100), nullable=True),
        sa.Column("decision", sa.String(length=30), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("rationale", sa.Text(), nullable=False),
        sa.Column("corrected_candidate", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["forecast_component_id"],
            ["forecast_components.forecast_component_id"],
        ),
        sa.ForeignKeyConstraint(
            ["proposal_artifact_id"],
            ["ai_artifacts.ai_artifact_id"],
        ),
        sa.ForeignKeyConstraint(
            ["review_artifact_id"],
            ["ai_artifacts.ai_artifact_id"],
        ),
        sa.PrimaryKeyConstraint("target_resolution_review_id"),
    )
    with op.batch_alter_table("target_resolution_reviews", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_target_resolution_reviews_forecast_component_id"),
            ["forecast_component_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_target_resolution_reviews_proposal_artifact_id"),
            ["proposal_artifact_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_target_resolution_reviews_review_artifact_id"),
            ["review_artifact_id"],
            unique=False,
        )

    with op.batch_alter_table("forecast_components", schema=None) as batch_op:
        batch_op.add_column(sa.Column("raw_target_label", sa.Text(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "target_resolution_status",
                sa.String(length=40),
                server_default="locked",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column("importance", sa.String(length=20), server_default="normal", nullable=False)
        )
        batch_op.add_column(sa.Column("high_importance_reason", sa.Text(), nullable=True))
        batch_op.alter_column("target_id", existing_type=sa.VARCHAR(length=20), nullable=True)
        batch_op.alter_column(
            "target_mapping_id", existing_type=sa.VARCHAR(length=20), nullable=True
        )
        batch_op.create_index(
            batch_op.f("ix_forecast_components_target_resolution_status"),
            ["target_resolution_status"],
            unique=False,
        )

    with op.batch_alter_table("forecast_issuances", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ai_artifact_id", sa.String(length=20), nullable=True))
        batch_op.alter_column("ai_import_id", existing_type=sa.VARCHAR(length=20), nullable=True)
        batch_op.create_index(
            batch_op.f("ix_forecast_issuances_ai_artifact_id"), ["ai_artifact_id"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_forecast_issuances_ai_artifact",
            "ai_artifacts",
            ["ai_artifact_id"],
            ["ai_artifact_id"],
        )
        batch_op.create_unique_constraint(
            "uq_issuance_artifact_ref", ["ai_artifact_id", "local_ref"]
        )

    with op.batch_alter_table("prompt_executions", schema=None) as batch_op:
        batch_op.alter_column("ai_import_id", existing_type=sa.VARCHAR(length=20), nullable=True)

    with op.batch_alter_table("run_sources", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "processing_status",
                sa.String(length=40),
                server_default="raw_imported",
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("latest_ai_artifact_id", sa.String(length=20), nullable=True))
        batch_op.create_index(
            batch_op.f("ix_run_sources_processing_status"), ["processing_status"], unique=False
        )
        batch_op.create_foreign_key(
            "fk_run_sources_latest_ai_artifact",
            "ai_artifacts",
            ["latest_ai_artifact_id"],
            ["ai_artifact_id"],
        )

    with op.batch_alter_table("target_mappings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("proposal_artifact_id", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("review_artifact_id", sa.String(length=20), nullable=True))
        batch_op.add_column(
            sa.Column("adjudication_artifact_id", sa.String(length=20), nullable=True)
        )
        batch_op.add_column(sa.Column("unevaluable_reason", sa.Text(), nullable=True))
        batch_op.alter_column("locked_at", existing_type=sa.DATETIME(), nullable=True)
        batch_op.create_foreign_key(
            "fk_target_mappings_proposal_artifact",
            "ai_artifacts",
            ["proposal_artifact_id"],
            ["ai_artifact_id"],
        )
        batch_op.create_foreign_key(
            "fk_target_mappings_review_artifact",
            "ai_artifacts",
            ["review_artifact_id"],
            ["ai_artifact_id"],
        )
        batch_op.create_foreign_key(
            "fk_target_mappings_adjudication_artifact",
            "ai_artifacts",
            ["adjudication_artifact_id"],
            ["ai_artifact_id"],
        )

    with op.batch_alter_table("targets", schema=None) as batch_op:
        batch_op.alter_column("ticker", existing_type=sa.VARCHAR(length=100), nullable=True)
        batch_op.alter_column("currency", existing_type=sa.VARCHAR(length=20), nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("targets", schema=None) as batch_op:
        batch_op.alter_column("currency", existing_type=sa.VARCHAR(length=20), nullable=False)
        batch_op.alter_column("ticker", existing_type=sa.VARCHAR(length=100), nullable=False)

    with op.batch_alter_table("target_mappings", schema=None) as batch_op:
        batch_op.drop_constraint("fk_target_mappings_adjudication_artifact", type_="foreignkey")
        batch_op.drop_constraint("fk_target_mappings_review_artifact", type_="foreignkey")
        batch_op.drop_constraint("fk_target_mappings_proposal_artifact", type_="foreignkey")
        batch_op.alter_column("locked_at", existing_type=sa.DATETIME(), nullable=False)
        batch_op.drop_column("unevaluable_reason")
        batch_op.drop_column("adjudication_artifact_id")
        batch_op.drop_column("review_artifact_id")
        batch_op.drop_column("proposal_artifact_id")

    with op.batch_alter_table("run_sources", schema=None) as batch_op:
        batch_op.drop_constraint("fk_run_sources_latest_ai_artifact", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_run_sources_processing_status"))
        batch_op.drop_column("latest_ai_artifact_id")
        batch_op.drop_column("processing_status")

    with op.batch_alter_table("prompt_executions", schema=None) as batch_op:
        batch_op.alter_column("ai_import_id", existing_type=sa.VARCHAR(length=20), nullable=False)

    with op.batch_alter_table("forecast_issuances", schema=None) as batch_op:
        batch_op.drop_constraint("uq_issuance_artifact_ref", type_="unique")
        batch_op.drop_constraint("fk_forecast_issuances_ai_artifact", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_forecast_issuances_ai_artifact_id"))
        batch_op.alter_column("ai_import_id", existing_type=sa.VARCHAR(length=20), nullable=False)
        batch_op.drop_column("ai_artifact_id")

    with op.batch_alter_table("forecast_components", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_forecast_components_target_resolution_status"))
        batch_op.alter_column(
            "target_mapping_id", existing_type=sa.VARCHAR(length=20), nullable=False
        )
        batch_op.alter_column("target_id", existing_type=sa.VARCHAR(length=20), nullable=False)
        batch_op.drop_column("high_importance_reason")
        batch_op.drop_column("importance")
        batch_op.drop_column("target_resolution_status")
        batch_op.drop_column("raw_target_label")

    with op.batch_alter_table("target_resolution_reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_target_resolution_reviews_review_artifact_id"))
        batch_op.drop_index(batch_op.f("ix_target_resolution_reviews_proposal_artifact_id"))
        batch_op.drop_index(batch_op.f("ix_target_resolution_reviews_forecast_component_id"))

    op.drop_table("target_resolution_reviews")
    with op.batch_alter_table("target_resolution_candidates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_target_resolution_candidates_proposal_artifact_id"))
        batch_op.drop_index(batch_op.f("ix_target_resolution_candidates_forecast_component_id"))

    op.drop_table("target_resolution_candidates")
    with op.batch_alter_table("target_resolution_adjudications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_target_resolution_adjudications_review_artifact_id"))
        batch_op.drop_index(batch_op.f("ix_target_resolution_adjudications_proposal_artifact_id"))
        batch_op.drop_index(batch_op.f("ix_target_resolution_adjudications_forecast_component_id"))
        batch_op.drop_index(
            batch_op.f("ix_target_resolution_adjudications_adjudication_artifact_id")
        )

    op.drop_table("target_resolution_adjudications")
    with op.batch_alter_table("segments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_segments_source_id"))
        batch_op.drop_index(batch_op.f("ix_segments_ai_artifact_id"))

    op.drop_table("segments")
    with op.batch_alter_table("ai_artifacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ai_artifacts_source_id"))
        batch_op.drop_index(batch_op.f("ix_ai_artifacts_run_id"))
        batch_op.drop_index(batch_op.f("ix_ai_artifacts_resolution_status"))
        batch_op.drop_index(batch_op.f("ix_ai_artifacts_prompt_id"))
        batch_op.drop_index(batch_op.f("ix_ai_artifacts_output_hash"))
        batch_op.drop_index(batch_op.f("ix_ai_artifacts_classification"))

    op.drop_table("ai_artifacts")
    # ### end Alembic commands ###
